### ISSUE TITLE
请问是否支持windows

### ISSUE THREAD

**Issue by dream0407** [hluwa/Wallbreaker#23]
git clone下来后，在WINDOWS加载插件提示错误
PS C:\Users\Administrator.TKKAM07971D8K4K\Desktop\frida> objection -g com.admin.test explore -P C:\Users\Administrator.TKKAM07971D8K4K\Wallbreaker     
Using USB device `SM A716S`
Agent injected and responds ok!
[plugin] C:\Users\Administrator.TKKAM07971D8K4K\Wallbreaker\agent does not appear to be a valid plugin. Missing __init__.py
[plugin] C:\Users\Administrator.TKKAM07971D8K4K\Wallbreaker\tests does not appear to be a valid plugin. Missing __init__.py
Traceback (most recent call last):
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\Scripts\objection.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\cli.py", line 134, in explore       
    load_plugin([p.path])
  File "C:\Users\Administrator.TKKAM07971D8K4K\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\commands\plugin_manager.py", line 36, in load_plugin
    namespace = plugin.namespace
AttributeError: module 'a60e6023' has no attribute 'namespace'
Asking jobs to stop...
Unloading objection agent...

**Comment by p1s1lver** [comment]
安装错了哥，我猜测一下你的错误，是没有在 plugins 底下新建一个 Wallbreaker 目录而是直接用的 Wallbreaker 里面的 Wallbreaker
